### ISSUE TITLE
Unable to generate grids

### ISSUE THREAD

**Issue by chintagunta** [bernardparent/CFDWARP#1]
Dear sir,

I am unable to generate the grid files out of the box. Kindly help me on this.
Thank you.

Kind regards,
Dr Abhishek

**./tecgrid2D grid.2D.sinewall 1.tec
Reading grid file grid.2D.sinewall..
Segmentation fault (core dumped)**

**Comment by TRPrasanna** [comment]
Yes, that doesn't seem to be working for me too. Alteratively, as a temporary workaround, you can do
`make config`
from root directory, choose some options that would work, and then
`make clean`
followed by
`make src`
which would result in the warp executable inside CFDWARP/src. This warp executable must be able to generate grids using
`./warp -r grid.2D.sinewall -op 1.tec`

**Comment by TRPrasanna** [comment]
The syntax in grid.2D.sinewall is a bit outdated. You could try putting :
```
i1=1;  
i2=40;  
j1=1;  
j2=30;  
dwa11=0.001;  
Grid(  
  Size ( i1,j1, i2,j2 );  
  Corners ( i1,j1, i2,j2, 0,0, 1,1);  
  JoinCorners ( i1,j1, i2,j1, FE,0.5,dwa11,1, N0,0.5,1,1 );  
  JoinCorners ( i1,j2, i2,j2, FE,0.5,dwa11,1, N0,0.5,1,1 );  
  Equation ( i1,j1, i2,j1, y, y=0.1*sin(x*20));  
  Join ( i1,j1, i2,j2, j, FE,0.7,dwa11,1 );  
);  
```
inside grid.2D.sinewall . This code has been taken from the GRIDG documentation in CFDWARP/lib/gridg/doc .

**Comment by chintagunta** [comment]
Worked, thank you for your help.

**Comment by bernardparent** [comment]
The next version will fix the grid examples in lib/gridg/eg. They are
indeed quite outdated.
